version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remakingeden
      PGDATA: /data/remakingeden
    ports:
      - '5432:5432'
    restart: unless-stopped